import { C } from "./shared.mjs";

export const slides = [
  {
    kicker: "Lesson 02",
    title: "Lesson 02: Partitioning, statistics and incremental loads",
    subtitle: "От DDL к evidence: pruning, partitions, statistics, late facts и validation.",
    type: "cards",
    cards: [
      ["Цель", "Научиться проектировать partitioned fact под workload, а не под красивый CREATE TABLE.", C.green],
      ["Практика", "Работаем с lesson02 SQL-lab: bad/good partition key, catalog checks, ANALYZE.", C.blue],
      ["Итог", "Ученик уходит с mini-project: DDL, EXPLAIN, load policy, residual risk.", C.green],
    ],
  },
  {
    kicker: "Mental model",
    title: "Partitioning и distribution отвечают за разные физические вопросы",
    subtitle: "Один режет таблицу на управляемые части, другой раскладывает строки по segments.",
    type: "two",
    left: ["Partition key", "partition pruning, retention, leaf partitions, быстрый DROP/DETACH старого окна.", C.green],
    right: ["Distribution key", "segment placement, parallelism, join locality, skew risk через gp_segment_id.", C.blue],
  },
  {
    kicker: "Workload first",
    title: "Partition key выбирают после workload contract",
    subtitle: "Сначала вопросы к отчетам и загрузке, потом DDL.",
    type: "flow",
    flow: [
      ["Predicates", "Какие WHERE фильтры повторяются каждый день?", C.green],
      ["Retention", "Что удаляем или архивируем по времени?", C.blue],
      ["Late facts", "Как часто факты приезжают задним числом?", C.amber],
      ["SLA load", "Когда publish и ANALYZE должны закончиться?", C.green],
      ["Validation", "Какие counts/sums доказывают корректность?", C.blue],
    ],
  },
  {
    kicker: "Bad design",
    title: "loaded_at часто удобен инженеру, но бесполезен отчету",
    subtitle: "Если бизнес фильтрует sale_date, partition by loaded_at не даст нужный pruning.",
    type: "code",
    code: "CREATE TABLE lesson02.fact_sales_bad_partition_key (...)\nWITH (appendoptimized=true, orientation=column)\nDISTRIBUTED BY (customer_id)\nPARTITION BY RANGE (loaded_at);\n\n-- typical report filter:\nWHERE sale_date >= DATE '2026-02-01'\n  AND sale_date <  DATE '2026-03-01';",
  },
  {
    kicker: "Good design",
    title: "PARTITION BY RANGE (sale_date) совпадает с reporting predicate",
    subtitle: "Теперь optimizer может отбросить лишние leaf partitions.",
    type: "code",
    code: "CREATE TABLE lesson02.fact_sales_partitioned (...)\nWITH (appendoptimized=true, orientation=column,\n      compresstype=zstd, compresslevel=1)\nDISTRIBUTED BY (customer_id)\nPARTITION BY RANGE (sale_date);",
  },
  {
    kicker: "EXPLAIN",
    title: "Pruning надо доказывать планом, а не надеждой",
    subtitle: "В demo хороший план сканирует 1 partition из 4.",
    type: "code",
    code: "EXPLAIN\nSELECT sum(amount)\nFROM lesson02.fact_sales_partitioned\nWHERE sale_date >= DATE '2026-02-01'\n  AND sale_date < DATE '2026-03-01';\n\n-- ищем: Number of partitions to scan: 1 (out of 4)",
  },
  {
    kicker: "Catalog checks",
    title: "pg_partition_tree и gp_toolkit.gp_partitions показывают структуру",
    subtitle: "Catalog evidence нужен в homework и production review.",
    type: "code",
    code: "SELECT *\nFROM pg_partition_tree('lesson02.fact_sales_partitioned'::regclass);\n\nSELECT *\nFROM gp_toolkit.gp_partitions\nWHERE schemaname = 'lesson02'\nORDER BY partitiontablename;",
  },
  {
    kicker: "Strategies",
    title: "RANGE, LIST, HASH и DEFAULT решают разные задачи",
    subtitle: "Выбор стратегии должен звучать как ответ на workload, а не как перечисление syntax.",
    type: "cards",
    cards: [
      ["RANGE", "Даты, retention, rolling windows, monthly partitions.", C.green],
      ["LIST", "Стабильные бизнес-категории: region, channel, tenant group.", C.blue],
      ["HASH", "Bucketization без естественного range/list. Не замена DISTRIBUTED BY.", C.amber],
      ["DEFAULT", "Safety net для неожиданных значений. Может скрыть data quality issue.", C.red],
    ],
  },
  {
    kicker: "Storage",
    title: "AOCO partitions ускоряют scan, но не лечат плохой key",
    subtitle: "Storage, partitioning и distribution — три разных рычага.",
    type: "cards",
    cards: [
      ["AOCO", "column-oriented append-optimized storage для scan-heavy fact.", C.green],
      ["Compression", "zstd помогает storage footprint и IO, но не убирает Motion.", C.blue],
      ["Skew", "Проверяется через gp_segment_id, а не через orientation=column.", C.amber],
    ],
  },
  {
    kicker: "Statistics",
    title: "ANALYZE после load — часть контракта загрузки",
    subtitle: "Без свежих estimates optimizer легко выбирает плохой join или Motion.",
    type: "code",
    code: "ANALYZE lesson02.fact_sales_partitioned;\n\nSELECT schemaname, relname, n_live_tup, last_analyze\nFROM pg_stat_user_tables\nWHERE schemaname = 'lesson02'\nORDER BY relname;",
  },
  {
    kicker: "Load pipeline",
    title: "Incremental load — это stage, publish, analyze и audit",
    subtitle: "Простой INSERT не отвечает на retry, late facts и validation.",
    type: "flow",
    flow: [
      ["Stage", "Загружаем окно в staging table.", C.green],
      ["Validate", "Сверяем counts, sums, duplicates.", C.blue],
      ["Publish", "Публикуем touched partitions.", C.amber],
      ["ANALYZE", "Обновляем statistics.", C.green],
      ["Audit", "Фиксируем evidence для retry.", C.blue],
    ],
  },
  {
    kicker: "Late facts",
    title: "late-arriving facts — требование, а не исключение",
    subtitle: "Факт с sale_date января может приехать в февральской загрузке.",
    type: "two",
    left: ["Плохой ответ", "Просто вставим строку еще раз и посмотрим, что будет. Дубли и stale stats появятся тихо.", C.red],
    right: ["Хороший ответ", "bounded reload window, partition-level replace или идемпотентный merge/upsert, validation, ANALYZE.", C.green],
  },
  {
    kicker: "Idempotency",
    title: "idempotency означает безопасный повторный запуск",
    subtitle: "Повтор load не должен удваивать факты или ломать audit.",
    type: "cards",
    cards: [
      ["Deterministic key", "sale_id/source_system/load_batch_id позволяют отделить новые строки от дублей.", C.green],
      ["Bounded window", "Перезагружаем только контролируемое окно late facts.", C.blue],
      ["Evidence", "До publish сохраняем row counts, sums и duplicate checks.", C.amber],
    ],
  },
  {
    kicker: "Retention",
    title: "Retention через partition boundary обычно лучше массового DELETE",
    subtitle: "DETACH/DROP старой leaf partition проще объяснить и контролировать.",
    type: "code",
    code: "-- admin snippet, not casual classroom command\nALTER TABLE lesson02.fact_sales_partitioned\n  DETACH PARTITION lesson02.fact_sales_partitioned_2026_01;\n\nDROP TABLE lesson02.fact_sales_partitioned_2026_01;",
  },
  {
    kicker: "Evidence",
    title: "Приемка физического дизайна строится на доказательствах",
    subtitle: "Если доказательств нет, это не production-ready решение.",
    type: "cards",
    cards: [
      ["DDL", "PARTITION BY, DISTRIBUTED BY, storage options.", C.green],
      ["Plan", "EXPLAIN показывает pruning и возможный Motion risk.", C.blue],
      ["Catalog", "pg_partition_tree, gp_toolkit.gp_partitions, tableoid.", C.amber],
      ["Load", "ANALYZE, validation, retry, residual risk.", C.green],
    ],
  },
  {
    kicker: "Simple path",
    title: "60 минут: replay, pruning, statistics, incremental load",
    subtitle: "Основной маршрут держит ученика в SQL и evidence.",
    type: "flow",
    flow: [
      ["Replay", "Что не доказали в Lesson 01?", C.green],
      ["Pruning", "Bad/good partition key.", C.blue],
      ["Stats", "ANALYZE и last_analyze.", C.amber],
      ["Load", "late facts и idempotency.", C.green],
      ["Homework", "mini-project.", C.blue],
    ],
  },
  {
    kicker: "Deep route",
    title: "Deep-dive расширяет урок до operational design review",
    subtitle: "Используй, если ученик уже не путает pruning, Motion и distribution.",
    type: "cards",
    cards: [
      ["Plan reading", "Смотреть partitions, estimates и Motion в одном объяснении.", C.green],
      ["Maintenance", "ATTACH/DETACH, default partition, retention windows.", C.blue],
      ["Mini-RFC", "Ученик защищает DDL и load policy как production design.", C.amber],
    ],
  },
  {
    kicker: "Summary",
    title: "Что ученик должен унести с Lesson 02",
    subtitle: "Не набор syntax, а инженерный способ защищать MPP physical design.",
    type: "cards",
    cards: [
      ["Разделять ключи", "Partition key != distribution key.", C.green],
      ["Доказывать", "EXPLAIN, catalog checks, gp_segment_id, last_analyze.", C.blue],
      ["Проектировать load", "late-arriving facts, idempotency, validation, residual risk.", C.amber],
    ],
  },
];
