export const SLIDES = [
  {
    type: "hero",
    section: "LESSON 04",
    title: "Apache Spark:\nот данных к плану выполнения",
    subtitle: "Практическое погружение в PySpark для начинающего Data Engineer",
    meta: "Core · 60 минут  |  Deep dive · +30 минут",
    sources: ["https://spark.apache.org/docs/4.2.0/"],
  },
  {
    type: "incident",
    section: "ЗАЧЕМ",
    title: "Локальный Python больше не укладывается в SLA",
    lead: "120 ГБ событий · 18 минут до дедлайна · один процесс",
    bullets: [
      "Память заканчивается раньше данных",
      "Повторный запуск начинается с нуля",
      "Ускорение упирается в один CPU и один диск",
    ],
    callout: "Нужен не “быстрый pandas”, а другая модель выполнения.",
    sources: [],
  },
  {
    type: "outcomes",
    section: "КОНТРАКТ ЛЕКЦИИ",
    title: "После лекции вы сможете объяснить Spark через evidence",
    items: [
      ["01", "Модель", "Driver, executors, partitions, jobs и stages"],
      ["02", "Код", "DataFrame-пайплайн без Python UDF"],
      ["03", "План", "Exchange, join strategy и AQE"],
      ["04", "Наблюдение", "Spark UI: где искать shuffle и skew"],
    ],
    sources: ["https://spark.apache.org/docs/4.2.0/cluster-overview.html"],
  },
  {
    type: "statement",
    section: "BIG DATA",
    title: "Big Data — это ограничение workload, а не ярлык размера",
    statement: "Данные становятся “big”, когда привычная архитектура перестаёт выполнять обещания.",
    axes: ["объём", "скорость", "разнообразие", "стоимость", "сбои"],
    footerNote: "Сначала формулируем SLA и профиль нагрузки — потом выбираем движок.",
    sources: [
      "https://www.nist.gov/publications/nist-big-data-interoperability-framework-volume-1-definitions",
    ],
  },
  {
    type: "timeline",
    section: "ИСТОРИЯ BIG DATA",
    title: "Big Data возник не в один день — термин догонял инженерную реальность",
    items: [
      ["1990-е", "Цифровые следы", "Web, логи, транзакции и сенсоры растут быстрее прежней инфраструктуры"],
      ["1998", "John Mashey", "Доклад “Big Data … and the Next Wave of InfraStress” популяризирует термин"],
      ["2001", "Doug Laney", "Volume, velocity, variety описывают три независимых давления на data management"],
      ["2010-е", "Платформенный термин", "Big Data объединяет storage, compute, analytics и governance"],
    ],
    sources: [
      "https://web.stanford.edu/class/ee380/9798win/lect08.html",
      "https://web.archive.org/web/20180206012552/http://blogs.gartner.com/doug-laney/files/2012/01/ad949-3D-Data-Management-Controlling-Data-Volume-Velocity-and-Variety.pdf",
      "https://www.nist.gov/publications/nist-big-data-interoperability-framework-volume-1-definitions",
    ],
  },
  {
    type: "matrix",
    section: "3V",
    title: "3V — диагностическая модель давления, а не определение по порогу",
    columns: ["Сигнал", "Что ломается", "Арх. ответ", "Вопрос архитектора"],
    rows: [
      ["Volume", "байты / строки", "один узел", "partitioning", "Где предел scale-up?"],
      ["Velocity", "события / сек", "batch SLA", "streaming", "Какова цена задержки?"],
      ["Variety", "форматы / схемы", "жёсткая модель", "schema + contracts", "Кто владеет изменением?"],
      ["Итог", "профиль нагрузки", "обещания системы", "масштабируемая архитектура", "Как измерим успех?"],
    ],
    sources: [
      "https://web.archive.org/web/20180206012552/http://blogs.gartner.com/doug-laney/files/2012/01/ad949-3D-Data-Management-Controlling-Data-Volume-Velocity-and-Variety.pdf",
      "https://www.nist.gov/publications/nist-big-data-interoperability-framework-volume-1-definitions",
    ],
  },
  {
    type: "glossary",
    section: "3V → 6V → 10V",
    title: "После 3V появились десятки V — единого канона 6V или 10V нет",
    terms: [
      ["Volume", "масштаб данных и стоимость хранения"],
      ["Velocity", "скорость поступления и допустимая задержка"],
      ["Variety", "форматы, источники и эволюция schema"],
      ["Veracity", "качество, происхождение и доверие"],
      ["Value", "измеримый эффект относительно стоимости"],
      ["Variability", "скачки нагрузки и изменение смысла"],
      ["Visualization", "способ сделать вывод воспринимаемым"],
      ["Vulnerability", "privacy, security и риск утечки"],
    ],
    sources: [
      "https://web.archive.org/web/20180206012552/http://blogs.gartner.com/doug-laney/files/2012/01/ad949-3D-Data-Management-Controlling-Data-Volume-Velocity-and-Variety.pdf",
      "https://www.nist.gov/publications/nist-big-data-interoperability-framework-volume-1-definitions",
    ],
  },
  {
    type: "outcomes",
    section: "ПОЧЕМУ BIG DATA",
    title: "Big Data родился из разрыва между ростом данных и возможностями одного узла",
    items: [
      ["01", "Источники", "Web, mobile, telemetry и дешёвые сенсоры создают непрерывные цифровые следы"],
      ["02", "Экономика", "Commodity-машины дешевле вертикального масштабирования, но чаще отказывают"],
      ["03", "Workload", "ETL, поиск, ML и ad hoc analytics требуют разных паттернов доступа"],
      ["04", "Обещание", "Сохранить throughput и fault tolerance при росте объёма и числа узлов"],
    ],
    sources: [
      "https://web.stanford.edu/class/ee380/9798win/lect08.html",
      "https://research.google/pubs/the-google-file-system/",
      "https://www.nist.gov/publications/nist-big-data-interoperability-framework-volume-1-definitions",
    ],
  },
  {
    type: "timeline",
    section: "ОТ ХРАНЕНИЯ К COMPUTE",
    title: "Google превратил ненадёжный кластер в программируемую платформу",
    items: [
      ["2003", "Google File System", "Блоки, репликация и перенос compute ближе к данным"],
      ["2004", "MapReduce", "Partitioning, scheduling, shuffle и retry становятся обязанностью runtime"],
      ["2006", "Apache Hadoop", "Open-source реализация HDFS + MapReduce переносит модель в индустрию"],
      ["Вывод", "Сбой — часть протокола", "Вычисление проектируют так, чтобы task можно было безопасно повторить"],
    ],
    sources: [
      "https://research.google/pubs/the-google-file-system/",
      "https://research.google/pubs/mapreduce-simplified-data-processing-on-large-clusters/",
      "https://hadoop.apache.org/",
    ],
  },
  {
    type: "flow",
    section: "MAPREDUCE · НА ПАЛЬЦАХ",
    title: "MapReduce — как почтовый центр: пометить, рассортировать, собрать итог",
    items: [
      ["input", "мешки писем"],
      ["map", "поставить индекс"],
      ["shuffle", "свести по адресу"],
      ["reduce", "собрать доставку"],
    ],
    callout: "Runtime делит работу, двигает группы по ключу и повторяет потерянные части.",
    sources: ["https://research.google/pubs/mapreduce-simplified-data-processing-on-large-clusters/"],
  },
  {
    type: "architecture",
    section: "MAPREDUCE · ТЕХНИЧЕСКИ",
    title: "Один MapReduce job фиксирует конвейер вокруг одной shuffle-границы",
    nodes: [
      ["Input splits", "блоки HDFS\nлокальность данных"],
      ["Map tasks", "parse / filter\nлокальный sort"],
      ["Shuffle", "partition / fetch\nmerge by key"],
      ["Reduce tasks", "aggregate\noutput в HDFS"],
    ],
    caption: "Сильная сторона — простой восстанавливаемый batch. Цена — materialization между цепочками jobs.",
    sources: [
      "https://research.google/pubs/mapreduce-simplified-data-processing-on-large-clusters/",
      "https://hadoop.apache.org/docs/stable/hadoop-mapreduce-client/hadoop-mapreduce-client-core/MapReduceTutorial.html",
    ],
  },
  {
    type: "compare",
    section: "MAPREDUCE → SPARK",
    title: "Spark атаковал не Map и Reduce, а стоимость повторного использования данных",
    left: {
      label: "Цепочка MapReduce jobs",
      headline: "job → materialize → job",
      bullets: ["Надёжный one-pass batch", "Простые retry boundaries", "Итерации перечитывают и сериализуют данные"],
    },
    right: {
      label: "Spark application",
      headline: "DAG → stages → tasks",
      bullets: ["План виден целиком", "Working set можно persist", "Lineage позволяет восстановить partition"],
    },
    sources: [
      "https://research.google/pubs/mapreduce-simplified-data-processing-on-large-clusters/",
      "https://www.usenix.org/conference/hotcloud-10/spark-cluster-computing-working-sets",
      "https://www.usenix.org/conference/nsdi12/technical-sessions/presentation/zaharia",
    ],
  },
  {
    type: "timeline",
    section: "ИСТОРИЯ SPARK",
    title: "Matei Zaharia и команда AMPLab начали Spark с боли iterative и interactive workloads",
    items: [
      ["2009", "UC Berkeley AMPLab", "Проект Matei Zaharia и исследовательской команды для cluster analytics"],
      ["2010", "Working Sets", "HotCloud paper и open source: данные можно переиспользовать между operations"],
      ["2012", "RDD + lineage", "NSDI Best Paper формализует fault-tolerant distributed memory"],
      ["2013–14", "Apache", "Incubator в 2013; top-level project в 2014; сообщество масштабирует engine"],
    ],
    sources: [
      "https://spark.apache.org/history",
      "https://www.usenix.org/conference/hotcloud-10/spark-cluster-computing-working-sets",
      "https://www.usenix.org/conference/nsdi12/technical-sessions/presentation/zaharia",
    ],
  },
  {
    type: "timeline",
    section: "ВЕРСИИ SPARK · I",
    title: "0.x и 1.x превратили исследовательский RDD engine в платформу данных",
    items: [
      ["0.7 · 2013", "PySpark + Streaming", "Python API и alpha Spark Streaming расширяют аудиторию и workload"],
      ["0.8 · 2013", "YARN + MLlib", "Spark входит в Hadoop estate и получает ML library"],
      ["1.0 · 2014", "Стабильный проект", "API и ecosystem закрепляют Spark как самостоятельный engine"],
      ["1.3 · 2015", "DataFrame + Spark SQL", "Schema и Catalyst делают оптимизацию доступной Python API"],
    ],
    sources: [
      "https://spark.apache.org/news/",
      "https://spark.apache.org/releases/spark-release-1-3-0.html",
      "https://people.csail.mit.edu/matei/papers/2015/sigmod_spark_sql.pdf",
    ],
  },
  {
    type: "timeline",
    section: "ВЕРСИИ SPARK · II",
    title: "2.x–4.x сместили центр тяжести от RDD к SQL engine и PySpark UX",
    items: [
      ["2.0 · 2016", "Unified structured APIs", "SparkSession, whole-stage codegen и experimental Structured Streaming"],
      ["3.0 · 2020", "Adaptive execution", "AQE, dynamic partition pruning, ANSI improvements и Python UX"],
      ["4.0 · 2025", "SQL + Connect + Python", "ANSI default, VARIANT, Python Data Source API и mature Connect"],
      ["4.2 · 2026", "Data platform surface", "CDC, geospatial, DSv2 transactions и Arrow IPC default"],
    ],
    sources: [
      "https://spark.apache.org/releases/spark-release-2-0-0.html",
      "https://spark.apache.org/releases/spark-release-3-0-0.html",
      "https://spark.apache.org/releases/spark-release-4-0-0.html",
      "https://spark.apache.org/releases/spark-release-4-2-0.html",
    ],
  },
  {
    type: "checklist",
    section: "ПОЧЕМУ SPARK ПОБЕДИЛ",
    title: "Победила комбинация модели выполнения, API и экосистемы",
    groups: [
      ["DAG / lineage", "богаче fixed Map→Reduce и дешевле восстанавливает coarse-grained datasets"],
      ["DF / Catalyst", "декларативный PySpark получает relational optimization"],
      ["Tungsten", "whole-stage codegen, меньше JVM overhead, эффективнее memory и CPU"],
      ["Unified engine", "batch, SQL, streaming и ML используют общую execution model"],
      ["Open ecosystem", "Apache governance, Hadoop/cloud storage, YARN/Kubernetes и Python API"],
    ],
    sources: [
      "https://www.usenix.org/conference/nsdi12/technical-sessions/presentation/zaharia",
      "https://people.csail.mit.edu/matei/papers/2015/sigmod_spark_sql.pdf",
      "https://people.csail.mit.edu/matei/papers/2015/vldb_spark.pdf",
      "https://spark.apache.org/history",
    ],
  },
  {
    type: "boundary",
    section: "МЕНТАЛЬНАЯ МОДЕЛЬ",
    title: "Spark — compute engine, а не база данных",
    inside: ["Планирует DAG", "Распределяет задачи", "Выполняет трансформации", "Повторяет потерянные tasks"],
    outside: ["Не владеет бизнес-данными", "Не заменяет каталог", "Не гарантирует OLTP", "Не выбирает SLA за вас"],
    sources: ["https://spark.apache.org/docs/4.2.0/cluster-overview.html"],
  },
  {
    type: "decision",
    section: "АРХИТЕКТУРНЫЙ ВЫБОР",
    title: "Иногда лучший Spark job — тот, который вы не запускаете",
    question: "Данные и SLA действительно требуют распределённого вычисления?",
    paths: [
      ["Нет", "SQL в DWH / DuckDB / Python", "Меньше инфраструктуры и быстрее обратная связь"],
      ["Да", "Spark", "Когда нужны параллелизм, fault tolerance и единый batch API"],
    ],
    sources: [],
  },
  {
    type: "architecture",
    section: "RUNTIME",
    title: "Один Spark application — один driver и набор executors",
    nodes: [
      ["Driver", "SparkSession\nDAG + scheduling"],
      ["Executor A", "partition 0\npartition 3"],
      ["Executor B", "partition 1\npartition 4"],
      ["Executor C", "partition 2\npartition 5"],
    ],
    caption: "Driver координирует. Executors считают. Данные движутся между ними только при необходимости.",
    sources: ["https://spark.apache.org/docs/4.2.0/cluster-overview.html"],
  },
  {
    type: "compare",
    section: "RUNTIME",
    title: "Cluster manager выдаёт ресурсы — Spark управляет вычислением",
    left: {
      label: "Cluster manager",
      headline: "Кому дать CPU и memory?",
      bullets: ["Standalone", "Kubernetes", "YARN"],
    },
    right: {
      label: "Spark application",
      headline: "Какие tasks выполнить?",
      bullets: ["Driver строит план", "Executors выполняют tasks", "Spark отслеживает прогресс"],
    },
    sources: ["https://spark.apache.org/docs/4.2.0/cluster-overview.html"],
  },
  {
    type: "layers",
    section: "API + CONTEXT",
    title: "В PySpark работаем через DataFrame — но понимаем все уровни API",
    rows: [
      ["SparkSession", "spark.read / spark.sql", "Главная точка входа PySpark"],
      ["SparkContext", "spark.sparkContext", "Связь application с cluster runtime"],
      ["DataFrame", "строки + schema", "Основной оптимизируемый API"],
      ["RDD", "partitioned objects", "Низкий уровень без Catalyst/schema"],
      ["Dataset[T]", "JVM typed API", "Scala/Java; отдельного API в Python нет"],
    ],
    sources: [
      "https://spark.apache.org/docs/4.2.0/api/python/reference/pyspark.sql/api/pyspark.sql.SparkSession.html",
      "https://spark.apache.org/docs/4.2.0/api/python/reference/api/pyspark.SparkContext.html",
      "https://spark.apache.org/docs/4.2.0/rdd-programming-guide.html",
      "https://spark.apache.org/docs/4.2.0/sql-programming-guide.html",
    ],
  },
  {
    type: "architecture",
    section: "SCHEDULER FLOW",
    title: "Driver назначает tasks — cluster manager лишь выделяет executors",
    nodes: [
      ["Action", "Driver создаёт job\nиз DAG"],
      ["DAGScheduler", "режет DAG на stages\nпо shuffle"],
      ["TaskScheduler", "создаёт TaskSet\nи выбирает slots"],
      ["Executors", "одна task читает\nодну partition"],
    ],
    caption: "Назначение учитывает свободные executor slots и locality; status/retry возвращаются driver. FIFO/FAIR выбирает очередь между jobs.",
    sources: [
      "https://spark.apache.org/docs/4.2.0/cluster-overview.html",
      "https://spark.apache.org/docs/4.2.0/job-scheduling.html",
      "https://github.com/apache/spark/blob/v4.2.0/core/src/main/scala/org/apache/spark/scheduler/DAGScheduler.scala",
      "https://github.com/apache/spark/blob/v4.2.0/core/src/main/scala/org/apache/spark/scheduler/TaskSchedulerImpl.scala",
    ],
  },
  {
    type: "partition",
    section: "ПАРАЛЛЕЛИЗМ",
    title: "Partition — минимальная порция данных для одной task",
    partitions: ["p0", "p1", "p2", "p3", "p4", "p5", "p6", "p7"],
    workers: ["Executor A", "Executor B", "Executor C", "Executor D"],
    rule: "Слишком мало partitions → недогруз. Слишком много → overhead и мелкие файлы.",
    sources: ["https://spark.apache.org/docs/4.2.0/rdd-programming-guide.html"],
  },
  {
    type: "statement",
    section: "DATAFRAME",
    title: "DataFrame — декларативный контракт, а не цикл по строкам",
    statement: "Вы описываете результат. Catalyst выбирает физический способ его получить.",
    axes: ["schema", "expressions", "logical plan", "optimizer", "physical plan"],
    footerNote: "Чем больше логики видно Catalyst, тем больше свободы для оптимизации.",
    sources: ["https://spark.apache.org/docs/4.2.0/api/python/getting_started/quickstart_df.html"],
  },
  {
    type: "flow",
    section: "LAZY EVALUATION",
    title: "Transformations строят план — action запускает работу",
    items: [
      ["read", "ленивый источник"],
      ["filter", "transformation"],
      ["groupBy", "transformation"],
      ["write", "action"],
    ],
    callout: "До action Spark может переписать и сократить план.",
    sources: ["https://spark.apache.org/docs/4.2.0/api/python/getting_started/quickstart_df.html"],
  },
  {
    type: "architectureCompare",
    section: "LAZY EVALUATION",
    title: "Lazy evaluation даёт optimizer увидеть весь pipeline до запуска",
    left: {
      label: "Код написан",
      nodes: [
        ["read", "источник объявлен"],
        ["select", "лишние columns видны"],
        ["filter", "условие записано позже"],
        ["groupBy", "результат не вычислен"],
      ],
    },
    right: {
      label: "План к action",
      nodes: [
        ["Prune", "читать нужные columns"],
        ["Pushdown", "filter ближе к source"],
        ["Choose", "join/aggregate strategy"],
        ["Execute", "action создаёт новый job"],
      ],
    },
    callout: "Lazy ≠ cached: каждый action запускает job и по умолчанию заново проходит lineage.",
    sources: [
      "https://spark.apache.org/docs/4.2.0/rdd-programming-guide.html",
      "https://spark.apache.org/docs/4.2.0/sql-performance-tuning.html",
    ],
  },
  {
    type: "pipelineCompare",
    section: "CACHE",
    title: "Два actions без persist повторяют lineage; cache меняет второй проход",
    left: {
      label: "Без cache",
      steps: ["source", "transform", "count", "transform", "write"],
      note: "count = job 1; write = job 2; общий upstream вычисляется снова.",
    },
    right: {
      label: "cache / persist",
      steps: ["source", "transform", "fill cache", "RAM/disk", "reuse"],
      note: "cache() ленив; первый action заполняет blocks, следующий читает их.",
    },
    callout: "Persist только при reuse: выигрыш повторного compute должен окупить storage, eviction и serialization.",
    sources: [
      "https://spark.apache.org/docs/4.2.0/rdd-programming-guide.html",
      "https://spark.apache.org/docs/4.2.0/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.cache.html",
      "https://spark.apache.org/docs/4.2.0/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.persist.html",
    ],
  },
  {
    type: "layers",
    section: "EXECUTION",
    title: "Один action создаёт job, stages и tasks",
    rows: [
      ["Action", "write.parquet(…)", "Точка запуска"],
      ["Job", "весь DAG для action", "Единица пользовательского результата"],
      ["Stage", "цепочка без shuffle", "Граница передачи данных"],
      ["Task", "stage × partition", "Единица исполнения"],
    ],
    sources: ["https://spark.apache.org/docs/4.2.0/job-scheduling.html"],
  },
  {
    type: "shuffle",
    section: "EXECUTION",
    title: "Shuffle появляется, когда строки меняют владельца",
    before: ["p0: A,A", "p1: B,C", "p2: A,C", "p3: B,B"],
    after: ["A: A,A,A", "B: B,B,B", "C: C,C"],
    triggers: ["groupBy", "join", "distinct", "repartition", "orderBy"],
    warning: "Shuffle = сеть + сериализация + disk spill + новая stage.",
    sources: ["https://spark.apache.org/docs/4.2.0/rdd-programming-guide.html#shuffle-operations"],
  },
  {
    type: "case",
    section: "СКВОЗНОЙ КЕЙС",
    title: "Контракт пайплайна: события → дневная выручка",
    input: ["events/*.json", "event_id, customer_id", "event_ts, amount, country"],
    output: ["daily_revenue/", "event_date, country", "orders, revenue"],
    constraints: ["явная schema", "валидные ключи", "идемпотентная запись"],
    sources: [],
  },
  {
    type: "code",
    section: "PYSPARK",
    title: "Явная schema делает контракт проверяемым",
    code: `EVENT_SCHEMA = StructType([\n    StructField("event_id", StringType(), False),\n    StructField("customer_id", StringType(), False),\n    StructField("event_ts", TimestampType(), False),\n    StructField("amount", DecimalType(18, 2), False),\n    StructField("country", StringType(), True),\n])\n\nevents = spark.read.schema(EVENT_SCHEMA).json(input_path)`,
    takeaways: ["Нет полного scan для inferSchema", "Nullability — часть контракта", "Типы стабильны между запусками"],
    sources: ["https://spark.apache.org/docs/4.2.0/sql-data-sources.html"],
  },
  {
    type: "code",
    section: "PYSPARK",
    title: "Built-in expressions сохраняют оптимизации Catalyst",
    code: `clean = (\n    events\n    .filter(F.col("event_id").isNotNull())\n    .filter(F.col("amount") > 0)\n    .withColumn("event_date", F.to_date("event_ts"))\n    .withColumn("country", F.coalesce("country", F.lit("UNKNOWN")))\n    .dropDuplicates(["event_id"])\n)`,
    takeaways: ["Операции видны optimizer", "Нет построчного Python callback", "Логика читается как data contract"],
    sources: ["https://spark.apache.org/docs/4.2.0/api/python/reference/pyspark.sql/functions.html"],
  },
  {
    type: "code",
    section: "PYSPARK",
    title: "Join и aggregation — место, где рождается стоимость",
    code: `result = (\n    clean\n    .join(F.broadcast(countries), "country", "left")\n    .groupBy("event_date", "country_name")\n    .agg(\n        F.count("*").alias("orders"),\n        F.sum("amount").alias("revenue"),\n    )\n)`,
    takeaways: ["Размер стороны join важнее синтаксиса", "groupBy почти всегда означает shuffle", "Broadcast устраняет shuffle большой стороны"],
    sources: ["https://spark.apache.org/docs/4.2.0/sql-performance-tuning.html"],
  },
  {
    type: "evidence",
    section: "ПЛАН",
    title: "Сначала читаем план — потом тратим кластер",
    steps: [
      ["01", "explain('formatted')", "Получить physical plan"],
      ["02", "Найти Exchange", "Увидеть shuffle boundaries"],
      ["03", "Проверить Join", "BroadcastHash или SortMerge"],
      ["04", "Сверить partitions", "Оценить parallelism"],
    ],
    sources: ["https://spark.apache.org/docs/4.2.0/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.explain.html"],
  },
  {
    type: "plan",
    section: "ПЛАН",
    title: "Exchange в physical plan — сигнал перераспределения данных",
    code: `== Physical Plan ==\nAdaptiveSparkPlan\n+- HashAggregate\n   +- Exchange hashpartitioning(event_date, country_name, 8)\n      +- HashAggregate\n         +- BroadcastHashJoin [country], [country], LeftOuter\n            :- Filter (amount > 0)\n            +- BroadcastExchange HashedRelationBroadcastMode`,
    highlights: ["Exchange", "BroadcastHashJoin", "8 partitions"],
    interpretation: "План подтверждает один shuffle для aggregation и broadcast маленького справочника.",
    sources: ["https://spark.apache.org/docs/4.2.0/sql-performance-tuning.html"],
  },
  {
    type: "flow",
    section: "ЗАПИСЬ",
    title: "Action материализует план — формат сохраняет будущие возможности",
    items: [
      ["plan", "оптимизирован"],
      ["tasks", "выполнены"],
      ["Parquet", "columnar + schema"],
      ["catalog", "данные доступны"],
    ],
    callout: "Пишите partitioned output только по реально используемым фильтрам.",
    sources: ["https://spark.apache.org/docs/4.2.0/sql-data-sources-parquet.html"],
  },
  {
    type: "ui",
    section: "НАБЛЮДАЕМОСТЬ",
    title: "Spark UI превращает “медленно” в проверяемую гипотезу",
    tabs: [
      ["Jobs", "Какая action и где упала"],
      ["Stages", "Shuffle, skew, spill и stragglers"],
      ["SQL", "План и метрики операторов"],
      ["Executors", "Memory, GC, input и failed tasks"],
    ],
    callout: "Начните со Stage с максимальной длительностью — затем сравните tasks.",
    sources: ["https://spark.apache.org/docs/4.2.0/web-ui.html"],
  },
  {
    type: "evidence",
    section: "ИНЖЕНЕРНЫЙ МЕТОД",
    title: "Хорошая диагностика связывает код, план и runtime",
    steps: [
      ["Код", "groupBy + join", "Что мы попросили"],
      ["План", "Exchange + join strategy", "Что выбрал optimizer"],
      ["UI", "shuffle read + task time", "Что произошло"],
      ["Изменение", "broadcast / repartition", "Как проверим эффект"],
    ],
    sources: [
      "https://spark.apache.org/docs/4.2.0/sql-performance-tuning.html",
      "https://spark.apache.org/docs/4.2.0/web-ui.html",
    ],
  },
  {
    type: "exit",
    section: "CORE · 60 МИН",
    title: "Выходной билет: объясните Spark без магии",
    questions: [
      "Почему transformations не запускают вычисление?",
      "Что создаёт границу stage?",
      "Где увидеть фактическую join strategy?",
      "Когда Spark — лишняя сложность?",
    ],
    next: "Практика: запустить pipeline, сохранить explain и найти evidence в Spark UI.",
    sources: [],
  },
  {
    type: "divider",
    section: "DEEP DIVE · +30 МИН",
    title: "От API к физике выполнения",
    subtitle: "Spark vs MapReduce на principal-уровне, затем Catalyst, shuffle, Python/JVM boundary, AQE и skew",
    sources: [],
  },
  {
    type: "layers",
    section: "SPARK vs MAPREDUCE · 4 УРОВНЯ",
    title: "Одна разница — четыре глубины объяснения",
    rows: [
      ["Обыватель", "MapReduce убирает стол после каждого блюда", "Spark может оставить нужные продукты рядом"],
      ["Data Engineer", "MR связывает jobs через materialized output", "Spark планирует DAG и переиспользует datasets"],
      ["Senior", "MR оптимизирует fixed map/shuffle/reduce job", "Spark делит DAG на stages по wide dependencies"],
      ["Principal", "Durable boundaries упрощают recovery, но растят I/O", "Lineage, optimizer и runtime stats меняют cost model"],
    ],
    sources: [
      "https://research.google/pubs/mapreduce-simplified-data-processing-on-large-clusters/",
      "https://www.usenix.org/conference/nsdi12/technical-sessions/presentation/zaharia",
    ],
  },
  {
    type: "architectureCompare",
    section: "АРХИТЕКТУРА",
    title: "MapReduce оркестрирует job; Spark driver оркестрирует application DAG",
    left: {
      label: "Hadoop MapReduce on YARN",
      nodes: [
        ["Client", "job config"],
        ["MRAppMaster", "map/reduce scheduling"],
        ["Map → Shuffle → Reduce", "containers + retries"],
        ["HDFS", "input / durable output"],
      ],
    },
    right: {
      label: "Spark application",
      nodes: [
        ["Driver", "logical + physical plan"],
        ["DAGScheduler", "jobs → stages"],
        ["Executors", "tasks + cache + shuffle"],
        ["Storage", "input / output"],
      ],
    },
    callout: "Cluster manager выдаёт ресурсы в обоих случаях; модель планирования и границы materialization различаются.",
    sources: [
      "https://hadoop.apache.org/docs/stable/hadoop-mapreduce-client/hadoop-mapreduce-client-core/MapReduceTutorial.html",
      "https://spark.apache.org/docs/4.2.0/cluster-overview.html",
      "https://spark.apache.org/docs/4.2.0/job-scheduling.html",
    ],
  },
  {
    type: "pipelineCompare",
    section: "PIPELINE",
    title: "На многошаговом пайплайне Spark убирает лишние durable boundaries",
    left: {
      label: "3 MapReduce jobs",
      steps: ["read", "job 1", "HDFS", "job 2", "HDFS", "job 3", "write"],
      note: "Каждый job завершает контракт durable output",
    },
    right: {
      label: "1 Spark DAG",
      steps: ["read", "stage 1", "shuffle", "stage 2", "shuffle", "stage 3", "write"],
      note: "Materialization — только где её требует wide dependency или контракт",
    },
    callout: "Разница максимальна при итерациях и reuse; минимальна в одном I/O-bound scan → aggregate → write.",
    sources: [
      "https://research.google/pubs/mapreduce-simplified-data-processing-on-large-clusters/",
      "https://www.usenix.org/conference/hotcloud-10/spark-cluster-computing-working-sets",
      "https://www.usenix.org/conference/nsdi12/technical-sessions/presentation/zaharia",
    ],
  },
  {
    type: "compare",
    section: "FAULT TOLERANCE",
    title: "Оба engine повторяют tasks — различается цена восстановления промежуточного состояния",
    left: {
      label: "MapReduce",
      headline: "Recovery через materialized boundaries",
      bullets: ["Map output можно пересчитать", "Job output обычно durable в HDFS", "Простая локализация сбоя, больше I/O"],
    },
    right: {
      label: "Spark",
      headline: "Recovery через lineage + recompute",
      bullets: ["Потерянная partition строится заново", "Shuffle files и executor cache не равны durable storage", "Длинный lineage иногда требует checkpoint"],
    },
    sources: [
      "https://research.google/pubs/mapreduce-simplified-data-processing-on-large-clusters/",
      "https://www.usenix.org/conference/nsdi12/technical-sessions/presentation/zaharia",
      "https://spark.apache.org/docs/4.2.0/rdd-programming-guide.html#rdd-persistence",
    ],
  },
  {
    type: "comparisonMatrix",
    section: "МАТРИЦА · EXECUTION",
    title: "Spark — не просто “MapReduce в RAM”",
    columns: ["MapReduce", "Spark", "Архитектурное следствие"],
    rows: [
      ["Граф", "fixed map → shuffle → reduce", "arbitrary DAG → stages", "меньше jobs-обвязки"],
      ["Materialization", "между jobs обычно durable", "shuffle/persist по необходимости", "разный I/O cost"],
      ["Reuse", "через external storage", "cache/persist + lineage", "итерации дешевле"],
      ["Оптимизация", "в основном внутри job", "Catalyst + AQE для structured API", "план может меняться runtime"],
      ["Fault tolerance", "retry + durable output", "retry + lineage recompute", "разный recovery path"],
      ["API surface", "key/value map и reduce", "DataFrame/SQL, RDD, streaming, ML", "выше productivity, больше engine magic"],
    ],
    sources: [
      "https://research.google/pubs/mapreduce-simplified-data-processing-on-large-clusters/",
      "https://www.usenix.org/conference/nsdi12/technical-sessions/presentation/zaharia",
      "https://people.csail.mit.edu/matei/papers/2015/sigmod_spark_sql.pdf",
      "https://spark.apache.org/docs/4.2.0/sql-performance-tuning.html#adaptive-query-execution",
    ],
  },
  {
    type: "comparisonMatrix",
    section: "МАТРИЦА · WORKLOAD",
    title: "Разница важна не всегда: смотрим на число проходов, reuse и latency",
    columns: ["MapReduce", "Spark", "Вердикт"],
    rows: [
      ["One-pass scan/sort", "сильно", "сильно", "часто паритет, I/O доминирует"],
      ["Multi-stage ETL", "работает, много boundaries", "DAG + SQL optimizer", "обычно Spark"],
      ["Iterative ML / graph", "дорогой reread", "persist working set", "сильное преимущество Spark"],
      ["Interactive SQL", "высокий startup + jobs", "reuse + optimizer", "Spark лучше, но DWH может быть лучше обоих"],
      ["Continuous streaming", "не нативный fit", "Structured Streaming", "Spark, Flink или streaming DB"],
      ["Tiny data / OLTP", "плохо", "плохо", "не использовать distributed batch engine"],
    ],
    sources: [
      "https://www.usenix.org/conference/hotcloud-10/spark-cluster-computing-working-sets",
      "https://www.usenix.org/conference/nsdi12/technical-sessions/presentation/zaharia",
      "https://spark.apache.org/docs/4.2.0/streaming/index.html",
    ],
  },
  {
    type: "compare",
    section: "КОГДА РАЗНИЦА ЕСТЬ",
    title: "Выбирайте по доминирующей стоимости, а не по названию технологии",
    left: {
      label: "Разница велика",
      headline: "Reuse + много stages + tight SLA",
      bullets: ["PageRank, gradient iterations, feature engineering", "Ad hoc исследования над одним working set", "SQL-пайплайн с несколькими joins и aggregations"],
    },
    right: {
      label: "Разница мала или оба плохи",
      headline: "One-pass I/O или другой workload",
      bullets: ["Один полный scan и write", "Данные малы для одного узла", "OLTP, point lookup, business orchestration"],
    },
    sources: [
      "https://www.usenix.org/conference/nsdi12/technical-sessions/presentation/zaharia",
      "https://spark.apache.org/docs/4.2.0/cluster-overview.html",
    ],
  },
  {
    type: "checklist",
    section: "PRINCIPAL CHECK",
    title: "Principal не спрашивает “что быстрее?” без cost model",
    groups: [
      ["Workload graph", "сколько passes, shuffles, joins, iterations и независимых outputs"],
      ["Data physics", "bytes scanned, cardinality, skew, compression, partitioning и locality"],
      ["Recovery", "что можно recompute, что обязано быть durable, каков blast radius"],
      ["Platform fit", "security, catalog, lineage, autoscaling, skills и эксплуатационная зрелость"],
      ["Evidence", "сравнить end-to-end cost, p95 latency и operator toil на репрезентативных данных"],
    ],
    sources: [
      "https://dataintensive.net/",
      "https://spark.apache.org/docs/4.2.0/monitoring.html",
      "https://spark.apache.org/docs/4.2.0/sql-performance-tuning.html",
    ],
  },
  {
    type: "layers",
    section: "SCHEDULER · INTERNALS",
    title: "От action до executor slot: границы ответственности scheduler stack",
    rows: [
      ["DAGScheduler", "Job → stages", "ShuffleDependency задаёт boundary"],
      ["Stage", "TaskSet", "Одна task на output partition"],
      ["TaskScheduler", "locality + slots", "FIFO/FAIR и resource offers"],
      ["SchedulerBackend", "launch / status", "Связь driver с executors"],
      ["Recovery", "retry / speculation", "Повтор task или lineage partition"],
    ],
    sources: [
      "https://spark.apache.org/docs/4.2.0/job-scheduling.html",
      "https://spark.apache.org/docs/4.2.0/cluster-overview.html",
      "https://github.com/apache/spark/blob/v4.2.0/core/src/main/scala/org/apache/spark/scheduler/DAGScheduler.scala",
      "https://github.com/apache/spark/blob/v4.2.0/core/src/main/scala/org/apache/spark/scheduler/TaskSchedulerImpl.scala",
      "https://github.com/apache/spark/blob/v4.2.0/core/src/main/scala/org/apache/spark/scheduler/SchedulerBackend.scala",
    ],
  },
  {
    type: "layers",
    section: "CATALYST",
    title: "Один DataFrame проходит четыре слоя плана",
    rows: [
      ["Parsed", "что написал пользователь", "ещё без разрешённых колонок"],
      ["Analyzed", "колонки и типы разрешены", "контракт проверен"],
      ["Optimized", "predicate pushdown, pruning", "логика переписана"],
      ["Physical", "join и exchange выбраны", "можно выполнять"],
    ],
    sources: ["https://spark.apache.org/docs/4.2.0/sql-ref-syntax-qry-explain.html"],
  },
  {
    type: "compare",
    section: "DAG",
    title: "Narrow dependency конвейеризуется; wide требует обмена",
    left: {
      label: "Narrow",
      headline: "filter → select → withColumn",
      bullets: ["Одна input partition", "Одна output partition", "Обычно одна stage"],
    },
    right: {
      label: "Wide",
      headline: "groupBy → join → orderBy",
      bullets: ["Много input partitions", "Перераспределение по ключу", "Новая stage после shuffle"],
    },
    sources: ["https://spark.apache.org/docs/4.2.0/rdd-programming-guide.html#shuffle-operations"],
  },
  {
    type: "boundary",
    section: "PYSPARK",
    title: "PySpark управляет JVM engine — граница становится дорогой построчно",
    inside: ["DataFrame expressions", "Arrow batch exchange", "Pandas UDF batch", "Catalyst-visible logic"],
    outside: ["Обычный Python UDF", "Row-by-row serialization", "Непрозрачная бизнес-логика", "Сложнее оптимизировать"],
    sources: [
      "https://spark.apache.org/docs/4.2.0/api/python/user_guide/udfandudtf.html",
      "https://spark.apache.org/docs/4.2.0/api/python/tutorial/sql/arrow_pandas.html",
    ],
  },
  {
    type: "shuffle",
    section: "SHUFFLE",
    title: "Shuffle — это сеть, файлы и синхронизация между stages",
    before: ["map output 0", "map output 1", "map output 2", "map output 3"],
    after: ["reduce 0", "reduce 1", "reduce 2", "reduce 3"],
    triggers: ["serialize", "write", "fetch", "merge", "spill"],
    warning: "Оптимизация shuffle начинается с объёма данных и распределения ключей.",
    sources: ["https://spark.apache.org/docs/4.2.0/rdd-programming-guide.html#shuffle-operations"],
  },
  {
    type: "architecture",
    section: "CACHE · INTERNALS",
    title: "Cache хранит partitions как blocks на executors — не обрывая lineage",
    nodes: [
      ["persist()", "только помечает\nDataFrame"],
      ["First action", "вычисляет каждую\npartition"],
      ["BlockManager", "memory / disk\nна executors"],
      ["Next action", "cache scan\nили recompute"],
    ],
    caption: "Следующий plan показывает InMemoryTableScan. Default: MEMORY_AND_DISK_DESER; потерянный block recompute по lineage; unpersist() освобождает storage.",
    sources: [
      "https://spark.apache.org/docs/4.2.0/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.persist.html",
      "https://spark.apache.org/docs/4.2.0/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.cache.html",
      "https://spark.apache.org/docs/4.2.0/rdd-programming-guide.html",
      "https://spark.apache.org/docs/4.2.0/configuration.html#memory-management",
    ],
  },
  {
    type: "plan",
    section: "JOIN",
    title: "SortMergeJoin масштабируется, но сортирует обе стороны",
    code: `+- SortMergeJoin [customer_id], [customer_id], Inner\n   :- Sort [customer_id ASC]\n   :  +- Exchange hashpartitioning(customer_id, 200)\n   +- Sort [customer_id ASC]\n      +- Exchange hashpartitioning(customer_id, 200)`,
    highlights: ["2 × Exchange", "2 × Sort", "200 partitions"],
    interpretation: "Обе стороны перераспределяются по ключу: это устойчиво для больших таблиц, но дорого.",
    sources: ["https://spark.apache.org/docs/4.2.0/sql-performance-tuning.html#optimizing-the-join-strategy"],
  },
  {
    type: "plan",
    section: "JOIN",
    title: "BroadcastHashJoin убирает shuffle большой стороны",
    code: `+- BroadcastHashJoin [country], [country], LeftOuter, BuildRight\n   :- FileScan parquet [event_id, country, amount]\n   +- BroadcastExchange HashedRelationBroadcastMode\n      +- FileScan parquet [country, country_name]`,
    highlights: ["BuildRight", "BroadcastExchange", "нет Exchange слева"],
    interpretation: "Маленький справочник копируется на executors; большая таблица остаётся на месте.",
    sources: ["https://spark.apache.org/docs/4.2.0/sql-performance-tuning.html#optimizing-the-join-strategy"],
  },
  {
    type: "flow",
    section: "AQE",
    title: "AQE меняет physical plan по фактической статистике",
    items: [
      ["initial plan", "оценки до запуска"],
      ["runtime stats", "размеры shuffle"],
      ["plan update", "join + partitions"],
      ["final plan", "адаптирован"],
    ],
    callout: "AQE умеет coalesce partitions, менять join strategy и обрабатывать skewed partitions.",
    sources: ["https://spark.apache.org/docs/4.2.0/sql-performance-tuning.html#adaptive-query-execution"],
  },
  {
    type: "compare",
    section: "АНТИПАТТЕРНЫ",
    title: "Skew и small files ломают масштабирование с разных сторон",
    left: {
      label: "Data skew",
      headline: "Одна task держит stage",
      bullets: ["Горячий ключ", "Длинный хвост task time", "Spill и OOM"],
    },
    right: {
      label: "Small files",
      headline: "Тысячи tasks делают мало",
      bullets: ["Overhead планирования", "Metadata pressure", "Медленный listing"],
    },
    sources: ["https://spark.apache.org/docs/4.2.0/sql-performance-tuning.html"],
  },
  {
    type: "checklist",
    section: "PRODUCTION",
    title: "Production-ready Spark начинается до spark-submit",
    groups: [
      ["Контракт", "schema · keys · nulls · idempotency"],
      ["План", "explain · join strategy · exchanges"],
      ["Ресурсы", "partitions · memory · cores"],
      ["Evidence", "UI · metrics · logs · output checks"],
      ["Эксплуатация", "retry · alerts · ownership · runbook"],
    ],
    sources: [
      "https://spark.apache.org/docs/4.2.0/configuration.html",
      "https://spark.apache.org/docs/4.2.0/monitoring.html",
    ],
  },
  {
    type: "divider",
    section: "APPENDIX",
    title: "Шпаргалки для практики",
    subtitle: "Термины, варианты запуска и инженерные решения",
    sources: [],
  },
  {
    type: "glossary",
    section: "ШПАРГАЛКА",
    title: "Минимальный словарь Spark",
    terms: [
      ["Application", "один запуск пользовательской программы"],
      ["Driver", "координатор приложения"],
      ["Executor", "процесс, который выполняет tasks"],
      ["Job", "вычисление для одной action"],
      ["Stage", "часть job между shuffle boundaries"],
      ["Task", "работа stage над одной partition"],
      ["Partition", "порция данных для parallel work"],
      ["Exchange", "узел physical plan с redistribution"],
    ],
    sources: ["https://spark.apache.org/docs/4.2.0/cluster-overview.html"],
  },
  {
    type: "matrix",
    section: "DEPLOYMENT",
    title: "Способ запуска меняет эксплуатацию, но не модель приложения",
    columns: ["Local", "Standalone", "YARN", "Kubernetes"],
    rows: [
      ["Для чего", "разработка", "учебный кластер", "Hadoop estate", "cloud-native"],
      ["Ресурсы", "один процесс", "Spark master", "ResourceManager", "K8s scheduler"],
      ["Изоляция", "минимальная", "процессы/hosts", "containers", "pods"],
      ["Сложность", "низкая", "средняя", "средняя", "выше"],
    ],
    sources: ["https://spark.apache.org/docs/4.2.0/cluster-overview.html#cluster-manager-types"],
  },
  {
    type: "decision",
    section: "CACHE",
    title: "Cache оправдан только повторным использованием дорогого результата",
    question: "Этот DataFrame будет вычислен снова — и его пересчёт дорог?",
    paths: [
      ["Нет", "Не cache", "Освободить executor memory для shuffle и execution"],
      ["Да", "persist + unpersist", "Проверить storage level и фактический reuse в UI"],
    ],
    sources: ["https://spark.apache.org/docs/4.2.0/rdd-programming-guide.html#rdd-persistence"],
  },
  {
    type: "flow",
    section: "ДАЛЬШЕ",
    title: "Structured Streaming сохраняет ту же DataFrame-модель",
    items: [
      ["source", "Kafka / files"],
      ["DataFrame", "transformations"],
      ["state", "watermark"],
      ["sink", "table / topic"],
    ],
    callout: "Меняется режим исполнения; базовые понятия plan, partition и state остаются.",
    sources: ["https://spark.apache.org/docs/4.2.0/streaming/index.html"],
  },
  {
    type: "sources",
    section: "ЧИТАТЬ ДАЛЬШЕ",
    title: "История и архитектура: первоисточники и книги",
    actions: [
      "Начать с Mashey и Laney: термин и исходные 3V",
      "Прочитать GFS и MapReduce как один архитектурный ответ",
      "Сравнить HotCloud 2010 и RDD paper 2012",
      "Закрепить модель систем и практику PySpark книгами",
    ],
    links: [
      ["Big Data history", "web.stanford.edu/class/ee380/9798win/lect08.html"],
      ["Spark research", "spark.apache.org/research.html"],
      ["Learning Spark, 2nd ed.", "oreilly.com/library/view/learning-spark-2nd"],
      ["Designing Data-Intensive Applications", "dataintensive.net"],
      ["Mining of Massive Datasets", "infolab.stanford.edu/~ullman/mmds/book.pdf"],
    ],
    sources: [
      "https://web.stanford.edu/class/ee380/9798win/lect08.html",
      "https://spark.apache.org/research.html",
      "https://www.oreilly.com/library/view/learning-spark-2nd/9781492050032/",
      "https://dataintensive.net/",
      "https://infolab.stanford.edu/~ullman/mmds/book.pdf",
    ],
  },
  {
    type: "sources",
    section: "ПРАКТИКА",
    title: "Следующий шаг — собрать собственную evidence chain",
    actions: [
      "Запустить core pipeline через mentor-lab.py",
      "Сохранить formatted explain до выполнения",
      "Найти самый дорогой stage в Spark UI",
      "Сформулировать одно изменение и критерий успеха",
    ],
    links: [
      ["Spark 4.2.0 docs", "spark.apache.org/docs/4.2.0"],
      ["Лаборатория", "labs/spark/README.md"],
      ["Workbook", "lessons/lesson-04/docs/student-workbook.md"],
      ["Домашнее задание", "lessons/lesson-04/homework/assignment.md"],
    ],
    sources: [
      "https://spark.apache.org/docs/4.2.0/",
      "https://spark.apache.org/docs/4.2.0/api/python/getting_started/install.html",
    ],
  },
];

export const CORE_SLIDE_COUNT = 39;
export const FULL_SLIDE_COUNT = 66;
