export const SLIDES = [
  {
    type: "hero",
    section: "LESSON 04",
    title: "Apache Spark:\nот данных к плану выполнения",
    subtitle: "Практическое погружение в PySpark для начинающего Data Engineer",
    meta: "Core · 60 минут  |  Deep dive · +30 минут",
    sources: ["https://spark.apache.org/docs/4.2.0/"],
  },
  {
    type: "incident",
    section: "ЗАЧЕМ",
    title: "Локальный Python больше не укладывается в SLA",
    lead: "120 ГБ событий · 18 минут до дедлайна · один процесс",
    bullets: [
      "Память заканчивается раньше данных",
      "Повторный запуск начинается с нуля",
      "Ускорение упирается в один CPU и один диск",
    ],
    callout: "Нужен не “быстрый pandas”, а другая модель выполнения.",
    sources: [],
  },
  {
    type: "outcomes",
    section: "КОНТРАКТ ЛЕКЦИИ",
    title: "После лекции вы сможете объяснить Spark через evidence",
    items: [
      ["01", "Модель", "Driver, executors, partitions, jobs и stages"],
      ["02", "Код", "DataFrame-пайплайн без Python UDF"],
      ["03", "План", "Exchange, join strategy и AQE"],
      ["04", "Наблюдение", "Spark UI: где искать shuffle и skew"],
    ],
    sources: ["https://spark.apache.org/docs/4.2.0/cluster-overview.html"],
  },
  {
    type: "statement",
    section: "BIG DATA",
    title: "Big Data — это ограничение workload, а не ярлык размера",
    statement: "Данные становятся “big”, когда привычная архитектура перестаёт выполнять обещания.",
    axes: ["объём", "скорость", "разнообразие", "стоимость", "сбои"],
    footerNote: "Сначала формулируем SLA и профиль нагрузки — потом выбираем движок.",
    sources: [],
  },
  {
    type: "timeline",
    section: "ИСТОРИЯ",
    title: "Распределённые системы сделали сбой штатным событием",
    items: [
      ["2003", "Google File System", "Данные разбиты на блоки, реплицированы и распределены"],
      ["2004", "MapReduce", "Планирование, partitioning и retry стали частью runtime"],
      ["Вывод", "Не предотвращать каждый сбой", "Проектировать вычисление так, чтобы его можно было повторить"],
    ],
    sources: [
      "https://research.google/pubs/the-google-file-system/",
      "https://research.google/pubs/mapreduce-simplified-data-processing-on-large-clusters/",
    ],
  },
  {
    type: "compare",
    section: "ИСТОРИЯ",
    title: "MapReduce автоматизировал масштабирование — но оставил цену итераций",
    left: {
      label: "MapReduce",
      headline: "Map → disk → Reduce",
      bullets: ["Надёжный batch", "Явные границы фаз", "Много промежуточного I/O"],
    },
    right: {
      label: "Spark",
      headline: "DAG → оптимизированный план",
      bullets: ["Переиспользование данных", "Несколько API на одном engine", "Интерактивная разработка"],
    },
    sources: [
      "https://research.google/pubs/mapreduce-simplified-data-processing-on-large-clusters/",
      "https://spark.apache.org/history",
    ],
  },
  {
    type: "timeline",
    section: "ИСТОРИЯ SPARK",
    title: "Spark вырос из задачи ускорить повторные вычисления",
    items: [
      ["2009", "UC Berkeley AMPLab", "Исследовательский проект для кластерной аналитики"],
      ["2010", "Open source", "Проект становится доступен сообществу"],
      ["2013", "Apache Software Foundation", "Spark переходит в Apache Incubator"],
      ["Сегодня", "Единый engine", "SQL, batch, streaming и ML на общей модели"],
    ],
    sources: ["https://spark.apache.org/history"],
  },
  {
    type: "boundary",
    section: "МЕНТАЛЬНАЯ МОДЕЛЬ",
    title: "Spark — compute engine, а не база данных",
    inside: ["Планирует DAG", "Распределяет задачи", "Выполняет трансформации", "Повторяет потерянные tasks"],
    outside: ["Не владеет бизнес-данными", "Не заменяет каталог", "Не гарантирует OLTP", "Не выбирает SLA за вас"],
    sources: ["https://spark.apache.org/docs/4.2.0/cluster-overview.html"],
  },
  {
    type: "decision",
    section: "АРХИТЕКТУРНЫЙ ВЫБОР",
    title: "Иногда лучший Spark job — тот, который вы не запускаете",
    question: "Данные и SLA действительно требуют распределённого вычисления?",
    paths: [
      ["Нет", "SQL в DWH / DuckDB / Python", "Меньше инфраструктуры и быстрее обратная связь"],
      ["Да", "Spark", "Когда нужны параллелизм, fault tolerance и единый batch API"],
    ],
    sources: [],
  },
  {
    type: "architecture",
    section: "RUNTIME",
    title: "Один Spark application — один driver и набор executors",
    nodes: [
      ["Driver", "SparkSession\nDAG + scheduling"],
      ["Executor A", "partition 0\npartition 3"],
      ["Executor B", "partition 1\npartition 4"],
      ["Executor C", "partition 2\npartition 5"],
    ],
    caption: "Driver координирует. Executors считают. Данные движутся между ними только при необходимости.",
    sources: ["https://spark.apache.org/docs/4.2.0/cluster-overview.html"],
  },
  {
    type: "compare",
    section: "RUNTIME",
    title: "Cluster manager выдаёт ресурсы — Spark управляет вычислением",
    left: {
      label: "Cluster manager",
      headline: "Кому дать CPU и memory?",
      bullets: ["Standalone", "Kubernetes", "YARN"],
    },
    right: {
      label: "Spark application",
      headline: "Какие tasks выполнить?",
      bullets: ["Driver строит план", "Executors выполняют tasks", "Spark отслеживает прогресс"],
    },
    sources: ["https://spark.apache.org/docs/4.2.0/cluster-overview.html"],
  },
  {
    type: "partition",
    section: "ПАРАЛЛЕЛИЗМ",
    title: "Partition — минимальная порция данных для одной task",
    partitions: ["p0", "p1", "p2", "p3", "p4", "p5", "p6", "p7"],
    workers: ["Executor A", "Executor B", "Executor C", "Executor D"],
    rule: "Слишком мало partitions → недогруз. Слишком много → overhead и мелкие файлы.",
    sources: ["https://spark.apache.org/docs/4.2.0/rdd-programming-guide.html"],
  },
  {
    type: "statement",
    section: "DATAFRAME",
    title: "DataFrame — декларативный контракт, а не цикл по строкам",
    statement: "Вы описываете результат. Catalyst выбирает физический способ его получить.",
    axes: ["schema", "expressions", "logical plan", "optimizer", "physical plan"],
    footerNote: "Чем больше логики видно Catalyst, тем больше свободы для оптимизации.",
    sources: ["https://spark.apache.org/docs/4.2.0/api/python/getting_started/quickstart_df.html"],
  },
  {
    type: "flow",
    section: "LAZY EVALUATION",
    title: "Transformations строят план — action запускает работу",
    items: [
      ["read", "ленивый источник"],
      ["filter", "transformation"],
      ["groupBy", "transformation"],
      ["write", "action"],
    ],
    callout: "До action Spark может переписать и сократить план.",
    sources: ["https://spark.apache.org/docs/4.2.0/api/python/getting_started/quickstart_df.html"],
  },
  {
    type: "layers",
    section: "EXECUTION",
    title: "Один action создаёт job, stages и tasks",
    rows: [
      ["Action", "write.parquet(…)", "Точка запуска"],
      ["Job", "весь DAG для action", "Единица пользовательского результата"],
      ["Stage", "цепочка без shuffle", "Граница передачи данных"],
      ["Task", "stage × partition", "Единица исполнения"],
    ],
    sources: ["https://spark.apache.org/docs/4.2.0/job-scheduling.html"],
  },
  {
    type: "shuffle",
    section: "EXECUTION",
    title: "Shuffle появляется, когда строки меняют владельца",
    before: ["p0: A,A", "p1: B,C", "p2: A,C", "p3: B,B"],
    after: ["A: A,A,A", "B: B,B,B", "C: C,C"],
    triggers: ["groupBy", "join", "distinct", "repartition", "orderBy"],
    warning: "Shuffle = сеть + сериализация + disk spill + новая stage.",
    sources: ["https://spark.apache.org/docs/4.2.0/rdd-programming-guide.html#shuffle-operations"],
  },
  {
    type: "case",
    section: "СКВОЗНОЙ КЕЙС",
    title: "Контракт пайплайна: события → дневная выручка",
    input: ["events/*.json", "event_id, customer_id", "event_ts, amount, country"],
    output: ["daily_revenue/", "event_date, country", "orders, revenue"],
    constraints: ["явная schema", "валидные ключи", "идемпотентная запись"],
    sources: [],
  },
  {
    type: "code",
    section: "PYSPARK",
    title: "Явная schema делает контракт проверяемым",
    code: `EVENT_SCHEMA = StructType([\n    StructField("event_id", StringType(), False),\n    StructField("customer_id", StringType(), False),\n    StructField("event_ts", TimestampType(), False),\n    StructField("amount", DecimalType(18, 2), False),\n    StructField("country", StringType(), True),\n])\n\nevents = spark.read.schema(EVENT_SCHEMA).json(input_path)`,
    takeaways: ["Нет полного scan для inferSchema", "Nullability — часть контракта", "Типы стабильны между запусками"],
    sources: ["https://spark.apache.org/docs/4.2.0/sql-data-sources.html"],
  },
  {
    type: "code",
    section: "PYSPARK",
    title: "Built-in expressions сохраняют оптимизации Catalyst",
    code: `clean = (\n    events\n    .filter(F.col("event_id").isNotNull())\n    .filter(F.col("amount") > 0)\n    .withColumn("event_date", F.to_date("event_ts"))\n    .withColumn("country", F.coalesce("country", F.lit("UNKNOWN")))\n    .dropDuplicates(["event_id"])\n)`,
    takeaways: ["Операции видны optimizer", "Нет построчного Python callback", "Логика читается как data contract"],
    sources: ["https://spark.apache.org/docs/4.2.0/api/python/reference/pyspark.sql/functions.html"],
  },
  {
    type: "code",
    section: "PYSPARK",
    title: "Join и aggregation — место, где рождается стоимость",
    code: `result = (\n    clean\n    .join(F.broadcast(countries), "country", "left")\n    .groupBy("event_date", "country_name")\n    .agg(\n        F.count("*").alias("orders"),\n        F.sum("amount").alias("revenue"),\n    )\n)`,
    takeaways: ["Размер стороны join важнее синтаксиса", "groupBy почти всегда означает shuffle", "Broadcast устраняет shuffle большой стороны"],
    sources: ["https://spark.apache.org/docs/4.2.0/sql-performance-tuning.html"],
  },
  {
    type: "evidence",
    section: "ПЛАН",
    title: "Сначала читаем план — потом тратим кластер",
    steps: [
      ["01", "explain('formatted')", "Получить physical plan"],
      ["02", "Найти Exchange", "Увидеть shuffle boundaries"],
      ["03", "Проверить Join", "BroadcastHash или SortMerge"],
      ["04", "Сверить partitions", "Оценить parallelism"],
    ],
    sources: ["https://spark.apache.org/docs/4.2.0/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.explain.html"],
  },
  {
    type: "plan",
    section: "ПЛАН",
    title: "Exchange в physical plan — сигнал перераспределения данных",
    code: `== Physical Plan ==\nAdaptiveSparkPlan\n+- HashAggregate\n   +- Exchange hashpartitioning(event_date, country_name, 8)\n      +- HashAggregate\n         +- BroadcastHashJoin [country], [country], LeftOuter\n            :- Filter (amount > 0)\n            +- BroadcastExchange HashedRelationBroadcastMode`,
    highlights: ["Exchange", "BroadcastHashJoin", "8 partitions"],
    interpretation: "План подтверждает один shuffle для aggregation и broadcast маленького справочника.",
    sources: ["https://spark.apache.org/docs/4.2.0/sql-performance-tuning.html"],
  },
  {
    type: "flow",
    section: "ЗАПИСЬ",
    title: "Action материализует план — формат сохраняет будущие возможности",
    items: [
      ["plan", "оптимизирован"],
      ["tasks", "выполнены"],
      ["Parquet", "columnar + schema"],
      ["catalog", "данные доступны"],
    ],
    callout: "Пишите partitioned output только по реально используемым фильтрам.",
    sources: ["https://spark.apache.org/docs/4.2.0/sql-data-sources-parquet.html"],
  },
  {
    type: "ui",
    section: "НАБЛЮДАЕМОСТЬ",
    title: "Spark UI превращает “медленно” в проверяемую гипотезу",
    tabs: [
      ["Jobs", "Какая action и где упала"],
      ["Stages", "Shuffle, skew, spill и stragglers"],
      ["SQL", "План и метрики операторов"],
      ["Executors", "Memory, GC, input и failed tasks"],
    ],
    callout: "Начните со Stage с максимальной длительностью — затем сравните tasks.",
    sources: ["https://spark.apache.org/docs/4.2.0/web-ui.html"],
  },
  {
    type: "evidence",
    section: "ИНЖЕНЕРНЫЙ МЕТОД",
    title: "Хорошая диагностика связывает код, план и runtime",
    steps: [
      ["Код", "groupBy + join", "Что мы попросили"],
      ["План", "Exchange + join strategy", "Что выбрал optimizer"],
      ["UI", "shuffle read + task time", "Что произошло"],
      ["Изменение", "broadcast / repartition", "Как проверим эффект"],
    ],
    sources: [
      "https://spark.apache.org/docs/4.2.0/sql-performance-tuning.html",
      "https://spark.apache.org/docs/4.2.0/web-ui.html",
    ],
  },
  {
    type: "exit",
    section: "CORE · 60 МИН",
    title: "Выходной билет: объясните Spark без магии",
    questions: [
      "Почему transformations не запускают вычисление?",
      "Что создаёт границу stage?",
      "Где увидеть фактическую join strategy?",
      "Когда Spark — лишняя сложность?",
    ],
    next: "Практика: запустить pipeline, сохранить explain и найти evidence в Spark UI.",
    sources: [],
  },
  {
    type: "divider",
    section: "DEEP DIVE · +30 МИН",
    title: "От API к физике выполнения",
    subtitle: "Разбираем Catalyst, shuffle, Python/JVM boundary, AQE и skew",
    sources: [],
  },
  {
    type: "layers",
    section: "CATALYST",
    title: "Один DataFrame проходит четыре слоя плана",
    rows: [
      ["Parsed", "что написал пользователь", "ещё без разрешённых колонок"],
      ["Analyzed", "колонки и типы разрешены", "контракт проверен"],
      ["Optimized", "predicate pushdown, pruning", "логика переписана"],
      ["Physical", "join и exchange выбраны", "можно выполнять"],
    ],
    sources: ["https://spark.apache.org/docs/4.2.0/sql-ref-syntax-qry-explain.html"],
  },
  {
    type: "compare",
    section: "DAG",
    title: "Narrow dependency конвейеризуется; wide требует обмена",
    left: {
      label: "Narrow",
      headline: "filter → select → withColumn",
      bullets: ["Одна input partition", "Одна output partition", "Обычно одна stage"],
    },
    right: {
      label: "Wide",
      headline: "groupBy → join → orderBy",
      bullets: ["Много input partitions", "Перераспределение по ключу", "Новая stage после shuffle"],
    },
    sources: ["https://spark.apache.org/docs/4.2.0/rdd-programming-guide.html#shuffle-operations"],
  },
  {
    type: "boundary",
    section: "PYSPARK",
    title: "PySpark управляет JVM engine — граница становится дорогой построчно",
    inside: ["DataFrame expressions", "Arrow batch exchange", "Pandas UDF batch", "Catalyst-visible logic"],
    outside: ["Обычный Python UDF", "Row-by-row serialization", "Непрозрачная бизнес-логика", "Сложнее оптимизировать"],
    sources: [
      "https://spark.apache.org/docs/4.2.0/api/python/user_guide/udfandudtf.html",
      "https://spark.apache.org/docs/4.2.0/api/python/tutorial/sql/arrow_pandas.html",
    ],
  },
  {
    type: "shuffle",
    section: "SHUFFLE",
    title: "Shuffle — это сеть, файлы и синхронизация между stages",
    before: ["map output 0", "map output 1", "map output 2", "map output 3"],
    after: ["reduce 0", "reduce 1", "reduce 2", "reduce 3"],
    triggers: ["serialize", "write", "fetch", "merge", "spill"],
    warning: "Оптимизация shuffle начинается с объёма данных и распределения ключей.",
    sources: ["https://spark.apache.org/docs/4.2.0/rdd-programming-guide.html#shuffle-operations"],
  },
  {
    type: "plan",
    section: "JOIN",
    title: "SortMergeJoin масштабируется, но сортирует обе стороны",
    code: `+- SortMergeJoin [customer_id], [customer_id], Inner\n   :- Sort [customer_id ASC]\n   :  +- Exchange hashpartitioning(customer_id, 200)\n   +- Sort [customer_id ASC]\n      +- Exchange hashpartitioning(customer_id, 200)`,
    highlights: ["2 × Exchange", "2 × Sort", "200 partitions"],
    interpretation: "Обе стороны перераспределяются по ключу: это устойчиво для больших таблиц, но дорого.",
    sources: ["https://spark.apache.org/docs/4.2.0/sql-performance-tuning.html#optimizing-the-join-strategy"],
  },
  {
    type: "plan",
    section: "JOIN",
    title: "BroadcastHashJoin убирает shuffle большой стороны",
    code: `+- BroadcastHashJoin [country], [country], LeftOuter, BuildRight\n   :- FileScan parquet [event_id, country, amount]\n   +- BroadcastExchange HashedRelationBroadcastMode\n      +- FileScan parquet [country, country_name]`,
    highlights: ["BuildRight", "BroadcastExchange", "нет Exchange слева"],
    interpretation: "Маленький справочник копируется на executors; большая таблица остаётся на месте.",
    sources: ["https://spark.apache.org/docs/4.2.0/sql-performance-tuning.html#optimizing-the-join-strategy"],
  },
  {
    type: "flow",
    section: "AQE",
    title: "AQE меняет physical plan по фактической статистике",
    items: [
      ["initial plan", "оценки до запуска"],
      ["runtime stats", "размеры shuffle"],
      ["plan update", "join + partitions"],
      ["final plan", "адаптирован"],
    ],
    callout: "AQE умеет coalesce partitions, менять join strategy и обрабатывать skewed partitions.",
    sources: ["https://spark.apache.org/docs/4.2.0/sql-performance-tuning.html#adaptive-query-execution"],
  },
  {
    type: "compare",
    section: "АНТИПАТТЕРНЫ",
    title: "Skew и small files ломают масштабирование с разных сторон",
    left: {
      label: "Data skew",
      headline: "Одна task держит stage",
      bullets: ["Горячий ключ", "Длинный хвост task time", "Spill и OOM"],
    },
    right: {
      label: "Small files",
      headline: "Тысячи tasks делают мало",
      bullets: ["Overhead планирования", "Metadata pressure", "Медленный listing"],
    },
    sources: ["https://spark.apache.org/docs/4.2.0/sql-performance-tuning.html"],
  },
  {
    type: "checklist",
    section: "PRODUCTION",
    title: "Production-ready Spark начинается до spark-submit",
    groups: [
      ["Контракт", "schema · keys · nulls · idempotency"],
      ["План", "explain · join strategy · exchanges"],
      ["Ресурсы", "partitions · memory · cores"],
      ["Evidence", "UI · metrics · logs · output checks"],
      ["Эксплуатация", "retry · alerts · ownership · runbook"],
    ],
    sources: [
      "https://spark.apache.org/docs/4.2.0/configuration.html",
      "https://spark.apache.org/docs/4.2.0/monitoring.html",
    ],
  },
  {
    type: "divider",
    section: "APPENDIX",
    title: "Шпаргалки для практики",
    subtitle: "Термины, варианты запуска и инженерные решения",
    sources: [],
  },
  {
    type: "glossary",
    section: "ШПАРГАЛКА",
    title: "Минимальный словарь Spark",
    terms: [
      ["Application", "один запуск пользовательской программы"],
      ["Driver", "координатор приложения"],
      ["Executor", "процесс, который выполняет tasks"],
      ["Job", "вычисление для одной action"],
      ["Stage", "часть job между shuffle boundaries"],
      ["Task", "работа stage над одной partition"],
      ["Partition", "порция данных для parallel work"],
      ["Exchange", "узел physical plan с redistribution"],
    ],
    sources: ["https://spark.apache.org/docs/4.2.0/cluster-overview.html"],
  },
  {
    type: "matrix",
    section: "DEPLOYMENT",
    title: "Способ запуска меняет эксплуатацию, но не модель приложения",
    columns: ["Local", "Standalone", "YARN", "Kubernetes"],
    rows: [
      ["Для чего", "разработка", "учебный кластер", "Hadoop estate", "cloud-native"],
      ["Ресурсы", "один процесс", "Spark master", "ResourceManager", "K8s scheduler"],
      ["Изоляция", "минимальная", "процессы/hosts", "containers", "pods"],
      ["Сложность", "низкая", "средняя", "средняя", "выше"],
    ],
    sources: ["https://spark.apache.org/docs/4.2.0/cluster-overview.html#cluster-manager-types"],
  },
  {
    type: "decision",
    section: "CACHE",
    title: "Cache оправдан только повторным использованием дорогого результата",
    question: "Этот DataFrame будет вычислен снова — и его пересчёт дорог?",
    paths: [
      ["Нет", "Не cache", "Освободить executor memory для shuffle и execution"],
      ["Да", "persist + unpersist", "Проверить storage level и фактический reuse в UI"],
    ],
    sources: ["https://spark.apache.org/docs/4.2.0/rdd-programming-guide.html#rdd-persistence"],
  },
  {
    type: "flow",
    section: "ДАЛЬШЕ",
    title: "Structured Streaming сохраняет ту же DataFrame-модель",
    items: [
      ["source", "Kafka / files"],
      ["DataFrame", "transformations"],
      ["state", "watermark"],
      ["sink", "table / topic"],
    ],
    callout: "Меняется режим исполнения; базовые понятия plan, partition и state остаются.",
    sources: ["https://spark.apache.org/docs/4.2.0/streaming/index.html"],
  },
  {
    type: "sources",
    section: "ПРАКТИКА",
    title: "Следующий шаг — собрать собственную evidence chain",
    actions: [
      "Запустить core pipeline через mentor-lab.py",
      "Сохранить formatted explain до выполнения",
      "Найти самый дорогой stage в Spark UI",
      "Сформулировать одно изменение и критерий успеха",
    ],
    links: [
      ["Spark 4.2.0 docs", "spark.apache.org/docs/4.2.0"],
      ["Лаборатория", "labs/spark/README.md"],
      ["Workbook", "lessons/lesson-04/docs/student-workbook.md"],
      ["Домашнее задание", "lessons/lesson-04/homework/assignment.md"],
    ],
    sources: [
      "https://spark.apache.org/docs/4.2.0/",
      "https://spark.apache.org/docs/4.2.0/api/python/getting_started/install.html",
    ],
  },
];

export const CORE_SLIDE_COUNT = 26;
export const FULL_SLIDE_COUNT = 42;
