import { C } from "./shared.mjs";

export const slides = [
  {
    kicker: "Урок 03",
    title: "Декомпозиция и тюнинг тяжёлых запросов в MPP",
    subtitle: "Greenplum 6.25: планы, GPORCA vs Legacy, статистика, storage, TEMP.",
    type: "cards",
    cards: [
      ["Цель", "Понять оптимизацию Greenplum по косточкам и доказывать rewrite планом.", C.green],
      ["Стенд", "labs/greenplum-625 (GP 6.25.3): seed, check, ORCA/Legacy demo.", C.blue],
      ["Итог", "Ученик выбирает optimizer и physical stage осознанно, не по привычке.", C.green],
    ],
  },
  {
    kicker: "Lab",
    title: "Self-service стенд Урока 03 — Greenplum 6.25",
    subtitle: "Отдельный lab greenplum-625, чтобы демо ORCA/Legacy было воспроизводимо.",
    type: "code",
    code: "python3 mentor-lab.py up greenplum-625\npython3 mentor-lab.py check greenplum-625\npython3 mentor-lab.py seed greenplum-625 --profile lesson03\npython3 mentor-lab.py psql greenplum-625\n\n# x86_64:\nGREENPLUM_625_IMAGE=andruche/greenplum:6.25.3-slim-amd64 \\\n  python3 mentor-lab.py up greenplum-625",
  },
  {
    kicker: "Mental model",
    title: "Тяжёлый OLAP = данные + сеть + оценки + выбор оптимизатора",
    subtitle: "SQL — вход; план — контракт на CPU, IO и interconnect.",
    type: "two",
    left: ["Что дорого", "Лишний Motion, плохой join order, stale stats, spill, широкая projection.", C.red],
    right: ["Рычаги", "optimizer on/off, ANALYZE, TEMP stages, DISTRIBUTED BY, Heap/AO/AOCO.", C.green],
  },
  {
    kicker: "Pipeline",
    title: "Как Greenplum оптимизирует запрос: стадии",
    subtitle: "QD строит план; QE исполняют slices. Ошибка на стадии optimize = дорогая сеть.",
    type: "flow",
    flow: [
      ["Parse", "SQL → parse tree.", C.green],
      ["Rewrite", "views/rules → query tree.", C.blue],
      ["Optimize", "Legacy или GPORCA → plan.", C.amber],
      ["Dispatch", "QD → gangs/slices.", C.green],
      ["Execute", "QE + Motion + gather.", C.blue],
    ],
  },
  {
    kicker: "Optimize stage",
    title: "Стадия Optimize — развилка Legacy vs GPORCA",
    subtitle: "GUC optimizer управляет, кто строит распределённый plan.",
    type: "code",
    code: "SHOW optimizer;              -- on | off\nSET optimizer = on;           -- GPORCA (Pivotal Optimizer)\nSET optimizer = off;          -- legacy Postgres-based planner\n\n-- В EXPLAIN ищите маркер оптимизатора:\n-- Settings: ... optimizer=on\n-- Optimizer status: PQO version ...",
  },
  {
    kicker: "Legacy",
    title: "Legacy Postgres planner: как думает",
    subtitle: "Динамическое программирование / жадные эвристики вокруг path trees PostgreSQL + GP Motion hooks.",
    type: "cards",
    cards: [
      ["Корни", "path/joinpath, costsize, selfuncs + cdbpath Motion.", C.green],
      ["Сильная сторона", "Простые/средние запросы, предсказуемый fallback.", C.blue],
      ["Слабость", "Взрыв пространства при многих joins; слабее глобальный reorder.", C.amber],
      ["Практика", "Часто хорош на 2–3 joins и локальных agg.", C.green],
    ],
  },
  {
    kicker: "GPORCA",
    title: "GPORCA: memo, transformations, cost-based search",
    subtitle: "Cascades-style optimizer: исследование эквивалентных планов в memo-структуре.",
    type: "cards",
    cards: [
      ["Memo", "Groups альтернативных выражений одного logical result.", C.green],
      ["Xforms", "Join reorder, aggregate pull-up/push-down, distribution enforcers.", C.blue],
      ["Cost", "Учитывает Motion/distribution как first-class cost.", C.amber],
      ["Сильная сторона", "Сложные star/snowflake, много joins, CTE-heavy SQL.", C.green],
    ],
  },
  {
    kicker: "Compare",
    title: "Где ORCA обычно выигрывает, а где Legacy",
    subtitle: "Не религия: измеряйте EXPLAIN/EXPLAIN ANALYZE на вашем workload.",
    type: "two",
    left: ["ORCA лучше", "Много joins, сложный star, partition-heavy, когда нужен глубокий reorder и distribution-aware cost.", C.green],
    right: ["Legacy лучше / безопаснее", "Простые запросы; ORCA fallback/features gaps; отладка «странного» ORCA plan; иногда ниже planning time.", C.amber],
  },
  {
    kicker: "Demo SQL",
    title: "Демо на стенде: один SQL — два оптимизатора",
    subtitle: "lesson03.v_star_join_orca_case специально перегружен joins.",
    type: "code",
    code: "\\i /mentor-lab/examples/lesson03-optimizer-legacy-vs-orca.sql\n\nSET optimizer = on;\nEXPLAIN SELECT * FROM lesson03.v_star_join_orca_case\nORDER BY revenue DESC LIMIT 20;\n\nSET optimizer = off;\nEXPLAIN SELECT * FROM lesson03.v_star_join_orca_case\nORDER BY revenue DESC LIMIT 20;",
  },
  {
    kicker: "ORCA+ / Legacy−",
    title: "Кейс: ORCA эффективен, Legacy проседает",
    subtitle: "Многоjoin star: Legacy залипает в плохом порядке → лишний Redistribute.",
    type: "cards",
    cards: [
      ["Симптом", "Большой Redistribute до фильтров/agg; странный join order.", C.red],
      ["ORCA", "Находит порядок с меньшей shuffle cost через memo search.", C.green],
      ["Evidence", "Сравнить Settings/Optimizer status и Motion bytes/rows.", C.blue],
      ["Не путать", "Выигрыш ORCA ≠ повод не делать TEMP/ANALYZE.", C.amber],
    ],
  },
  {
    kicker: "Legacy+ / ORCA−",
    title: "Кейс: Legacy достаточен, ORCA избыточен",
    subtitle: "Простой aggregate по dimension: planning overhead ORCA не окупается.",
    type: "code",
    code: "SET optimizer = off;\nEXPLAIN SELECT region, count(*)\nFROM lesson03.dim_customer\nGROUP BY region;\n\n-- Здесь оба плана близки; смотрите planning time\n-- и стабильность, а не «модный» optimizer=on.",
  },
  {
    kicker: "Pros/Cons",
    title: "Плюсы и минусы: Legacy planner",
    subtitle: "Честный trade-off для Senior review.",
    type: "two",
    left: ["Плюсы", "Проще ментальная модель; быстрый planning на простых SQL; зрелый fallback; легче объяснить path tree.", C.green],
    right: ["Минусы", "Слабее на many-join; меньше глобальных transform; чаще локально-оптимальный join order.", C.red],
  },
  {
    kicker: "Pros/Cons",
    title: "Плюсы и минусы: GPORCA",
    subtitle: "Мощный search space имеет цену.",
    type: "two",
    left: ["Плюсы", "Глубокий join reorder; distribution-aware costing; сильнее на сложном OLAP/CTE.", C.green],
    right: ["Минусы", "Дороже planning; feature gaps → fallback; сложнее debug; иногда неожиданный plan shape.", C.red],
  },
  {
    kicker: "Fallback",
    title: "ORCA fallback и minidump — обязательная грамотность",
    subtitle: "Если ORCA не может оптимизировать, Greenplum уходит в Legacy.",
    type: "cards",
    cards: [
      ["Признак", "В EXPLAIN: Optimizer status / fallback reason.", C.amber],
      ["GUC", "optimizer_minidump=onerror для диагностики.", C.blue],
      ["Практика", "Не «чините SQL вслепую» — сначала читайте reason.", C.green],
      ["Prod", "Фиксируйте optimizer setting в session/role policy.", C.green],
    ],
  },
  {
    kicker: "Case",
    title: "Сквозной case: месячный OLAP по продажам и клиентам",
    subtitle: "Монолит для layered EXPLAIN + сравнения optimizer.",
    type: "code",
    code: "-- lesson03.v_heavy_olap_monolith\nSELECT c.region, d.category,\n       sum(f.amount) AS revenue,\n       rank() OVER (PARTITION BY c.region ORDER BY sum(f.amount) DESC)\nFROM lesson03.fact_sales f\nJOIN lesson03.dim_customer c ON c.customer_id = f.customer_id\nJOIN lesson03.dim_product  d ON d.product_id  = f.product_id\nWHERE f.sale_date >= DATE '2026-02-01'\n  AND f.sale_date <  DATE '2026-03-01'\n  AND c.segment <> 'test'\nGROUP BY c.region, d.category;",
  },
  {
    kicker: "Decomposition",
    title: "Декомпозиция: сужаем → соединяем → считаем → доказываем",
    subtitle: "Каждый этап должен уменьшать cardinality или убирать Motion.",
    type: "flow",
    flow: [
      ["Filter", "Окно и anti-test.", C.green],
      ["Shape", "TEMP grain.", C.blue],
      ["Join", "Узкий set.", C.amber],
      ["Agg", "Локально где можно.", C.green],
      ["Prove", "EXPLAIN до/после.", C.blue],
    ],
  },
  {
    kicker: "EXPLAIN",
    title: "Сложный план: слои Senior readout",
    subtitle: "0) Optimizer. 1) Motion. 2) Join order. 3) Estimates. 4) Scan/storage.",
    type: "cards",
    cards: [
      ["Optimizer", "on/off, fallback, PQO version.", C.green],
      ["Motion", "Redistribute/Broadcast/Gather и ключ.", C.blue],
      ["Estimates", "rows vs actual; selectivity traps.", C.amber],
      ["Scan", "partition pruning / AOCO projection.", C.green],
    ],
  },
  {
    kicker: "Estimates",
    title: "Если rows врут — тюнинг SQL почти бессмысленен",
    subtitle: "Плохая selectivity ломает и Legacy, и ORCA — но по-разному.",
    type: "code",
    code: "EXPLAIN ANALYZE\nSELECT ...;\n\n-- Ищем:\n--   rows vs actual rows\n--   расхождение x10–x100 на join input\n-- Затем: pg_stats / ANALYZE, и только потом rewrite.",
  },
  {
    kicker: "Motion",
    title: "Платим сетью: цель — перенести Motion на меньший set",
    subtitle: "ORCA может выбрать другой enforcer; TEMP фиксирует ваш контракт.",
    type: "two",
    left: ["До", "Redistribute широкого fact; Broadcast раздутой dim.", C.red],
    right: ["После", "TEMP окна + ANALYZE → меньше shuffle bytes.", C.green],
  },
  {
    kicker: "Statistics",
    title: "Оптимизатор питается MCV, histogram, n_distinct",
    subtitle: "И Legacy, и ORCA читают pg_statistic; мусор на входе = мусор в plan.",
    type: "cards",
    cards: [
      ["n_distinct", "Кардинальность; ломается на skew.", C.green],
      ["MCV", "Частые значения для equality/IN.", C.blue],
      ["Histogram", "Range predicates.", C.amber],
      ["correlation", "Physical order vs logical.", C.green],
    ],
  },
  {
    kicker: "Catalog",
    title: "pg_stats → pg_statistic → слоты на диске",
    subtitle: "Читаем статистику как plan: сначала human view, затем raw slots.",
    type: "code",
    code: "SELECT attname, n_distinct, most_common_vals, histogram_bounds\nFROM pg_stats\nWHERE schemaname='lesson03' AND tablename='fact_sales';\n\nSELECT staattnum, stakind1, stanumbers1, stavalues1\nFROM pg_statistic\nWHERE starelid='lesson03.fact_sales'::regclass;",
  },
  {
    kicker: "Engine",
    title: "ANALYZE path в коде Greenplum 6.25",
    subtitle: "sample → compute_stats → catalog heap tuple (возможно TOAST).",
    type: "cards",
    cards: [
      ["analyze.c", "Sampling и расчёт MCV/histogram.", C.green],
      ["selfuncs.c", "Selectivity functions для costing.", C.blue],
      ["pg_statistic", "Источник истины planner/ORCA metadata.", C.amber],
      ["QD/QE", "План на QD; данные и файлы на segments.", C.green],
    ],
  },
  {
    kicker: "Storage",
    title: "Heap / AO / AOCO на GP 6.25",
    subtitle: "В 6.x синтаксис: appendonly=true (не appendoptimized).",
    type: "cards",
    cards: [
      ["Heap", "Dims, updates, staging.", C.green],
      ["AO row", "Bulk append row-oriented.", C.blue],
      ["AOCO", "Scan-heavy fact + projection.", C.amber],
      ["Не лечит", "Плохой optimizer choice / Motion / skew.", C.red],
    ],
  },
  {
    kicker: "AOCO GP6",
    title: "Физическая раскладка AOCO и типы данных",
    subtitle: "Column files + compression; text/numeric varlena; широкий payload не читается зря.",
    type: "code",
    code: "CREATE TABLE lesson03.fact_sales (...)\nWITH (\n  appendonly=true,\n  orientation=column,\n  compresstype=zstd,\n  compresslevel=1\n)\nDISTRIBUTED BY (customer_id)\nPARTITION BY RANGE (sale_date) (...);",
  },
  {
    kicker: "TEMP",
    title: "TEMP — physical stage с ANALYZE и distribution",
    subtitle: "Фиксируем промежуточный контракт, который optimizer пересчитывает заново.",
    type: "cards",
    cards: [
      ["Зачем", "Новый grain + новый plan.", C.green],
      ["ANALYZE", "Обязателен после наполнения.", C.blue],
      ["Distribution", "Под следующий join key.", C.amber],
      ["Риск", "TEMP без фильтра увеличивает стоимость.", C.red],
    ],
  },
  {
    kicker: "TEMP internals",
    title: "pg_temp, файлы сегментов, spill ≠ TEMP TABLE",
    subtitle: "Явная TEMP relation и hash/sort spill files — разные механизмы.",
    type: "cards",
    cards: [
      ["Namespace", "pg_temp_NNN session-local.", C.green],
      ["Файлы", "Temporary relfilenode на segments.", C.blue],
      ["Spill", "work_mem miss → temp files исполнителей.", C.amber],
      ["GPDB", "QD координирует, данные на QE.", C.green],
    ],
  },
  {
    kicker: "Rewrite",
    title: "Паттерн rewrite + проверка optimizer",
    subtitle: "Before/after при фиксированном SET optimizer.",
    type: "code",
    code: "SET optimizer = on;  -- зафиксировали\nCREATE TEMP TABLE tmp_sales_feb AS\nSELECT customer_id, product_id, amount\nFROM lesson03.fact_sales\nWHERE sale_date >= DATE '2026-02-01'\n  AND sale_date <  DATE '2026-03-01'\nDISTRIBUTED BY (customer_id);\nANALYZE tmp_sales_feb;\nEXPLAIN ...",
  },
  {
    kicker: "Simple path",
    title: "60 минут на GP 6.25",
    subtitle: "Case → optimizer → EXPLAIN → stats → TEMP → proof.",
    type: "flow",
    flow: [
      ["Up/seed", "greenplum-625", C.green],
      ["ORCA", "on vs off", C.blue],
      ["Plan", "слои", C.amber],
      ["TEMP", "rewrite", C.green],
      ["Proof", "evidence", C.blue],
    ],
  },
  {
    kicker: "Deep route",
    title: "Deep-dive Principal: internals end-to-end",
    subtitle: "ORCA memo/xforms, pg_statistic slots, AOCO files, TEMP spill, design review.",
    type: "cards",
    cards: [
      ["ORCA", "fallback, minidump, join_order GUCs.", C.green],
      ["Stats files", "stakind/stavalues/TOAST.", C.blue],
      ["Storage", "appendonly column layout.", C.amber],
      ["RFC", "rewrite + optimizer policy.", C.green],
    ],
  },
  {
    kicker: "Summary",
    title: "Что унести с Урока 03",
    subtitle: "Оптимизация Greenplum — это pipeline + два optimizer + физика данных.",
    type: "cards",
    cards: [
      ["Стадии", "parse → rewrite → optimize → dispatch → execute.", C.green],
      ["Выбор", "ORCA vs Legacy измерять, не верить.", C.blue],
      ["Физика", "stats/storage/TEMP — вход оптимизатора.", C.amber],
    ],
  },
];
